name: heck
version: "1.0"
summary: A simple C++ program to count number of lines in project/files.

description: A simple C++ program to count number of lines in project/files.

confinement: devmode
base: core18
    
parts:
  heck:
    plugin: cmake 
    source: ./
    build-packages:
      - clang
      - make
  
apps:
  heck:
    command: heck
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/heck"
      "DISABLE_WAYLAND": "1"